- Dockerfile
https://github.com/hadolint/hadolint/wiki/DL3017
https://github.com/hadolint/hadolint/wiki/DL3019
---
Awesome idea, btw!
> linting Dockerfile

- Dockerfile
Using latest [CloudFormation Resource Specification](https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/cfn-resource-specification.html) versions
because sometimes the latest versions haven't made it into a `cfn-lint` release yet
> cfn-lint --update-specs

- Dockerfile
because sometimes the latest IAM information hasn't made it into a `cfn-lint` release yet
> cfn-lint --update-iam-policies

- Dockerfile
This should make the startup time faster as it won't need to install python3 at build time.
This also follows the upstream docker image: https://github.com/aws-cloudformation/cfn-python-lint/blob/master/Dockerfile
> Update Docker base image to python:3.8-alpine

- README.md
Github actions will give an yaml syntax error on a non quoted string that begins with an "*".
> Fix YAML syntax in Usage Example

- .github/workflows/main.yml
Updating the Actions workflow to push an image to GitHub Packages, copied from https://github.com/actions/starter-workflows/blob/d7ac62140faf23b67c29e892d4ce68342eb09609/ci/docker-publish.yml#L38-L77. Closes #23
> Push image to GitHub Packages

- .devcontainer/Dockerfile
- .devcontainer/devcontainer.json
- README.md
- dist/index.js
- dist/licenses.txt
- package-lock.json
This Pull Request proposes a configuration for [GitHub Codespaces](https://docs.github.com/en/github/developing-online-with-codespaces/about-codespaces), files created by [Using a pre-built container configuration](https://docs.github.com/en/github/developing-online-with-codespaces/configuring-codespaces-for-your-project#using-a-pre-built-container-configuration), see [devcontainer.json reference](https://code.visualstudio.com/docs/remote/devcontainerjson-reference) for specifics.
[When Codespaces becomes generally available, you will be billed for storage and compute usage](https://docs.github.com/en/github/developing-online-with-codespaces/about-billing-for-codespaces), so I'll probably delete these configurations then .. but for now, this makes it easy to get up and running with …
> feat(dev): GitHub Codespaces Configuration

- README.md
- entrypoint.sh
Adding a quick note in the README regarding v1 deprecation, then having the Action print a notice as well via `entrypoint.sh`. Admittedly not terribly visible.
closes #55
> Deprecate v1

- examples/template.yml
Workflow runs in this repository are now failing due to
```
W2531 EOL runtime (nodejs10.x) specified. Runtime is EOL since 2021-05-31 and updating will be disabled at 2021-06-30. Please consider updating to nodejs14.x
Error: ./examples/template.yml:64:7
```
(https://github.com/ScottBrenner/cfn-lint-action/pull/61/checks?check_run_id=2708313079#step:4:6)
As this file was copied from https://github.com/awslabs/aws-cloudformation-templates/blob/master/community/services/Lambda/LambdaSample.yaml#L62-L63, we can fix-forward here.
https://docs.aws.amazon.com/lambda/latest/dg/lambda-runtimes.html
> fix: W2531 EOL runtime (nodejs10.x) specified

- .github/workflows/main.yml
Proposing changing the "Tests" workflow to simply run on all `push` events
- Removing the `branches` restriction, might as well run everywhere
- Removing `pull_request` event as it would "duplicate" `push`, running twice
> feat(CI): Run "Tests" on all push events

- .github/workflows/codeql-analysis.yml
The CodeQL workflow fails on the "push" event for Dependabot branches - https://github.com/ScottBrenner/cfn-lint-action/actions/workflows/codeql-analysis.yml with an error message like:
```
Error: Workflows triggered by Dependabot on the "push" event run with read-only access. Uploading Code Scanning results requires write access. To use Code Scanning with Dependabot, please ensure you are using the "pull_request" event for this workflow and avoid triggering on the "push" event for Dependabot branches. See https://docs.github.com/en/code-security/secure-coding/configuring-code-scanning#scanning-on-push for more information on how to configure these events.
```
(https://github.com/ScottBrenner/cfn-lint-action/runs/2764966785?check_suite_focus=true#step:3:55)
So, this pull request proposes …
> fix(CI): Trigger CodeQL on everything except the "push" event for Dependabot branches

- README.md
As described in https://github.com/aws-cloudformation/cfn-lint#basic-usage we need to "enable globbing" when calling `cfn-lint` on all `yaml` files in `path` and all subdirectories (recursive) like this.
Closes #90
> fix(docs): enable globbing in "Upgrading from Version 1?" section

- .github/workflows/main.yml
https://github.com/actions/virtual-environments/issues/4312
> Windows Server 2016 Active support ends on 11 Jan 2022 and Windows Server 2022 VM image is going out of beta later this year
Semi-related to https://github.com/ScottBrenner/cfn-lint-action/issues/141, maybe
> feat(CI): Replace windows-2016 with windows-2022

- README.md
By default, GitHub Actions uses a Bash shell and setopt is for ZSH shells, this updates the README with the correct command to use when globbing support is required.
> fix(docs): Use shopt for globbing support

- .github/workflows/main.yml
- examples/template.yml
https://github.com/ScottBrenner/cfn-lint-action/commit/9e5528120cdf2c3bb1ebb65befcd97db9d232c87 again - this time with https://docs.github.com/en/actions/using-github-hosted-runners/about-github-hosted-runners#supported-runners-and-hardware-resources & https://github.com/aws-cloudformation/cfn-lint/releases/tag/v0.71.1 -  to address https://github.com/ScottBrenner/cfn-lint-action/actions/runs/3459939916/jobs/5775898478#step:4:7
> fix: W2531 EOL runtime (nodejs12.x) specified

- .github/workflows/main.yml
Using the latest https://github.com/aws-cloudformation/cfn-lint/releases here.
> Bump cfn-lint version used in workflows/main.yml

- dist/index.js
- index.js
Fixes #273  
If there are errors in the template file, code for adding matchers doesn't get executed . Simply calling the `setup()` function after adding the matchers fixes the problem.
> fix: Fix annotations

- .github/cfn-lint.json
This PR enables warning annotations as an alternative to errors. If the severity is not specified in the problem matcher, it defaults to `error`. Only values accepted for severity  is `error` and `warning` case-insenitive, but unfortunately `cfn-lint` does not output any of those. It only produces a single letter for the type of the problem. Therefore, we can't directly use the matched group in the severity field. After some digging around, I've found that we can specify the severity field in the same level as owner. We can specify two owners, one for warnings and informational and one for errors.
I also took the liberty of including the error code in the message to make it more convenient to search the issue in [cfn-lint rules](https://github.com/aws-cloudformation/cfn-lint/blob/main/docs …
> feat(problem-matchers): Add warnings to problem matchers

- dist/index.js
- lib/utils/installCLI.js
- lib/utils/runCommand.js
- tests/runCommand.test.js
- tests/setup.test.js
Resolving https://github.com/ScottBrenner/cfn-lint-action/actions/runs/5579137792/jobs/10194286881#step:5:87.
```
$ npm run all
> cfn-lint-action@2.1.0 all /workspaces/cfn-lint-action
> npm run format && npm test && npm run build
> cfn-lint-action@2.1.0 format /workspaces/cfn-lint-action
> prettier --write .
.devcontainer/devcontainer.json 63ms
.eslintrc.json 3ms
action.yml 36ms
CHANGELOG.md 33ms
CODE_OF_CONDUCT.md 57ms
CONTRIBUTING.md 8ms
index.js 14ms
lib/setup.js 9ms
lib/utils/getInput.js 8ms
lib/utils/getInputs.js 8ms
lib/utils/helpers.js 16ms
lib/utils/installCLI.js 36ms
lib/utils/runCommand.js 6ms
package-lock.json 159ms
package.json 4ms
README.md 95ms
SECURITY.md 4ms
tests/getInput.test.js 14ms
tests/helpers.test.js 24ms
tests/runCommand.test.js 18ms
tests/setup.test.js 28ms
> …
```
> Fix failing tests

- .husky/pre-commit
- dist/index.js
- package.json
Implements migrations from https://github.com/typicode/husky/releases/tag/v9.0.1 to for v10 compatibility described in https://github.com/typicode/husky/releases/tag/v9.1.2
> FIX: Husky v10 prep

- .github/workflows/main.yml
- README.md
- action.yml
- dist/index.js
- dist/licenses.txt
- lib/utils/getInputs.js
- lib/utils/installCLI.js
- tests/setup.test.js
Extending the `version` input to allow [optional dependencies](https://github.com/aws-cloudformation/cfn-lint?tab=readme-ov-file#optional-dependencies) and [version specifier](https://peps.python.org/pep-0440/#version-specifiers), while defaulting to the current full installation.
Closes https://github.com/ScottBrenner/cfn-lint-action/issues/188
> Extend version input to allow dependencies and specifier
